function fun_save_proda_transiesnt_summary(save_pathway, online_tot_eco_c, online_tot_veg_c, online_tot_lit_c, online_npp, online_soc_stock, offline_soc_stock_proda, offline_soc_stock_default, offline_residence_time_proda, offline_residence_time_default, offline_soc_capacity_proda, offline_soc_capacity_default)

transient_summary.online_tot_eco_c = online_tot_eco_c;
transient_summary.online_tot_veg_c = online_tot_veg_c;
transient_summary.online_tot_lit_c = online_tot_lit_c;
transient_summary.online_npp = online_npp;
transient_summary.online_soc_stock = online_soc_stock;
transient_summary.offline_soc_stock_proda = offline_soc_stock_proda;
transient_summary.offline_soc_stock_default = offline_soc_stock_default;
transient_summary.offline_residence_time_proda = offline_residence_time_proda;
transient_summary.offline_residence_time_default = offline_residence_time_default;
transient_summary.offline_soc_capacity_proda = offline_soc_capacity_proda;
transient_summary.offline_soc_capacity_default = offline_soc_capacity_default;


save(save_pathway, 'transient_summary');
end
